config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :campaigns do
    resources :prototypes do
      resources :contents do
        resources :comments
      end
    end
  end
  root to: "site#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :prototypes
  
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :prototype
  has_many :comments
  has_attached_file :attachment
  do_not_validate_attachment_file_type :attachment
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :compaign, optional: true
  has_many :contents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :campaings
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_user!
    redirect_to root_path unless user_signed_in?
  end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
  end
end

app/controllers/campaigns_controller.rb
require 'pry'

class CampaignsController < ApplicationController
  before_action :authenticate_user!

  # vista de todas las capañas
  def index
    @currentUser = current_user.id
    @campaigns = Campaign.where(user_id: @currentUser)
  end

  def new
    @my_campaign = Campaign.new
  end

  def create
    @my_campaign = Campaign.new(
      name: params[:campaign][:name],
      description: params[:campaign][:description],
      start_date: params[:campaign][:start_date],
      end_date: params[:campaign][:end_date],
      user_id: current_user.id
    )
    @my_campaign.save
    redirect_to "/campaigns"
  end

  def edit

  end

  def update

  end

  # vista de una camapaña
  def show
    @my_campaign = Campaign.find_by(id: params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @my_content = Content.find_by(id: params[:content_id])
    @my_comment = @my_content.comments.new(comment_params)
    @my_comment.user = current_user
    @my_comment.save
    redirect_to "/campaigns/#{params[:campaign_id]}/prototypes/#{params[:prototype_id]}/contents/#{params[:content_id]}"
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_text)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def new
    @my_campaign = Campaign.find_by(id: params[:campaign_id])
    @my_prototype = Prototype.find_by(id: params[:prototype_id])
    @my_content = @my_prototype.contents.new
  end

  def create
    @my_prototype = Prototype.find_by(id: params[:prototype_id])
    @my_content = @my_prototype.contents.new(content_params)
    @my_content.save
    redirect_to "/campaigns/#{params[:campaign_id]}/prototypes/#{params[:prototype_id]}"
  end

  def show
    @my_campaign = Campaign.find_by(id: params[:campaign_id])
    @my_content = Content.find_by(id: params[:id])
    @my_comments = Comment.where(content_id: @my_content.id)
    @my_comment = @my_content.comments.new
  end

  private

  def content_params
    params.require(:content).permit(:name, :description, :attachment)
  end 
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  
  def new
    @my_campaign = Campaign.find_by(id: params[:campaign_id])
    @my_prototype = @my_campaign.prototypes.new
  end

  def create
    @my_campaign = Campaign.find_by(id: params[:campaign_id])
    @my_prototype = @my_campaign.prototypes.new(prototype_params)
    @my_prototype.save
    redirect_to "/campaigns/#{params[:campaign_id]}/prototypes/#{@my_prototype.id}"
  end

  def edit

  end

  def update

  end

  def remove

  end

  # vista del prototipo
  def show
    @my_prototype = Prototype.find_by(id: params[:id])
  end

  private

  def prototype_params
    params.require(:prototype).permit(:name, :description)
  end 

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/campaigns/index.html.erb
<div class="container-fluid">
  <%= link_to "Create campaign!", new_campaign_path %>
</div>

<div class="container-fluid">
  <% @campaigns.each do |campaign| %>    
    <div class="row" style="display: flex; flex-wrap:wrap;">
        
      <div class="col-sm-4" >
        <a href="/campaigns/<%= campaign.id %>"><h3><%= campaign.name %></h3></a>
      </div>
    </div>
    <div class="row" style="display: flex; flex-wrap:wrap;">
        
      <div class="col-sm-12" >
        <h4><%= campaign.description %></h4>
      </div>
    </div>
    <div class="row" style="display: flex; flex-wrap:wrap;">
        
      <div class="col-sm-6" >
        <h4>Start Date: <%= campaign.start_date %></h4>
      </div>
      <div class="col-sm-6" >
        <h4>End Date: <%= campaign.end_date %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/campaigns/new.html.erb
<h1>Create a new Campaign</h1>
<%= form_for @my_campaign do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_date %>
  <%= f.date_field :start_date, hide_label: true, class: 'datepicker' %>

  <%= f.label :end_date %>
  <%= f.date_field :end_date %>
  
  <%= f.button %>
<% end %>

app/views/campaigns/show.html.erb
<h1>Campaign details</h1>
<h2>Name: <%= @my_campaign.name %></h2>
<h3>Description: <%= @my_campaign.description %></h3>
<h3>Start Date: <%= @my_campaign.start_date %></h3>
<h3>End Date: <%= @my_campaign.end_date %></h3>
<h1>Prototypes</h1>
<h3><%= link_to "Add Prototype", new_campaign_prototype_path(@my_campaign) %></h3>
<div class="container-fluid">
  <% @my_campaign.prototypes.each do |prototype| %>    
    <div class="row" style="display: flex; flex-wrap:wrap;">
        
      <div class="col-sm-4" >
        <a href="/campaigns/<%= @my_campaign.id %>/prototypes/<%= prototype.id %>"><h3><%= prototype.name %></h3></a>
      </div>
    </div>
    <div class="row" style="display: flex; flex-wrap:wrap;">
        
      <div class="col-sm-12" >
        <h4><%= prototype.description %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/contents/new.html.erb
<h1>Create a new Prototype</h1>
<%= form_for [@my_campaign, @my_prototype, @my_content] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <%= f.label :attachment %>
  <%= f.file_field :attachment %>

  <%= f.button %>
<% end %>

app/views/contents/show.html.erb
<h1>Content details</h1>
<h2>Name: <%= @my_content.name %></h2>
<h3>Description: <%= @my_content.description %></h3>
<h3>File Attached: <%= link_to "See file", @my_content.attachment.url(:original, false) %></h3>
<h2>Comments</h2>
<%= form_for @my_comment, url: campaign_prototype_content_comments_path(@my_campaign.id, @my_content.prototype_id, @my_content) do |f| %>
  <%= f.label :comment_text %>
  <%= f.text_area :comment_text %>
  
  <%= f.button %>
<% end %>
<div class="container-fluid">
    <% @my_comments.each do |comment| %>    
      <div class="row" style="display: flex; flex-wrap:wrap;">
          
        <div class="col-sm-4" >
          <h3><%= comment.user.name %></h3>
        </div>
        <div class="col-sm-8" >
          <h3><%= comment.comment_text %></h3>
        </div>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampaignMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render  "site/header-logged-in" %> 
    <% else %>
      <%= render  "site/header-logged-out" %>
    <% end %>
    <%= yield %>
    <%= render "site/footer" %>
  </body>
</html>

app/views/prototypes/new.html.erb
<h1>Create a new Prototype</h1>
<%= form_for [@my_campaign, @my_prototype] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <h3>Once created you will be able to attch content files to this prototype</h3>

  <%= f.button %>
<% end %>

app/views/prototypes/show.html.erb
<h1>Prototype details</h1>
<h2>Name: <%= @my_prototype.name %></h2>
<h3>Description: <%= @my_prototype.description %></h3>
<h1>Contents</h1>

<h3><%= link_to "Add Content", new_campaign_prototype_content_path(@my_prototype.campaign_id, @my_prototype) %></h3>

<div class="container-fluid">
  <% @my_prototype.contents.each do |content| %>    
    <div class="row" style="display: flex; flex-wrap:wrap;">
        
      <div class="col-sm-4" >
        <a href="/campaigns/<%= @my_prototype.campaign_id %>/prototypes/<%= @my_prototype.id %>/contents/<%= content.id %>"><h3><%= content.name %></h3></a>
      </div>
    </div>
  <% end %>
</div>

app/views/site/_footer.html.erb
<footer style="background: #67b26f;background: -webkit-linear-gradient(to right, #67b26f, #4ca2cd);  background: linear-gradient(to right, #67b26f, #4ca2cd); padding-top: 30px; padding-bottom: 35px;">
  <div class="row">
    <div class="col-sm-4 text-center">
      <p style="color:white; font-size:20px;">Contacta con nosotros</p>
      <p style="color:white; font-size:13px;">hola@wolalab.com</p>
      <p style="color:white; font-size:13px;">Madrid</p>
    </div>
    <div class="col-sm-4 text-center">
      <p style="color:white; font-size:20px;">Síguenos</p>
      <a href="#" style="color:white; font-size:13px;"><p>Twitter</p></a>
      <a href="#" style="color:white; font-size:13px;"><p>Facebook</p></a>
      <a href="#" style="color:white; font-size:13px;"><p>Github</p></a>
    </div>
    <div class="col-sm-4 text-center">
      <p style="color:white; font-size:20px;">Wolalab</p>
      <a href="/privacy/explanation" style="color:white; font-size:13px;"><p>Políticas</p></a>
      <a href="/policies/terms-of-use" style="color:white; font-size:13px;"><p>Términos de Uso</p></a>
      <a href="/policies/cookies" style="color:white; font-size:13px;"><p>Cookies</p></a>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 text-center">
      <img class="logo" style="width:85px; height:85px;border-radius: 100px;background-color: white;padding: 10px;" src="" alt="Wolalab">
    </div>

  </div>
</footer>

app/views/site/_header-logged-in.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top" style="background: #67b26f;background: -webkit-linear-gradient(to right, #67b26f, #4ca2cd);  background: linear-gradient(to right, #67b26f, #4ca2cd);">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="border: none; background-color: transparent;">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand" style="height:inherit;">
          <img class="header-logo" src="{% static 'images/logo.png' %}" alt="Wolalab">
        </a>
      </div>
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="true">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Sign out!", destroy_user_session_path, :method => :delete %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/site/_header-logged-out.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top" style="background: #67b26f;background: -webkit-linear-gradient(to right, #67b26f, #4ca2cd);  background: linear-gradient(to right, #67b26f, #4ca2cd);">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="border: none; background-color: transparent;">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand" style="height:inherit;">
          <img class="header-logo" src="{% static 'images/logo.png' %}" alt="Wolalab">
        </a>
      </div>
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="true">
        <ul class="nav navbar-nav">
          <li>
            <a href="/users/sign_in" class="log-in-button">Login</a>
          </li>
          <li>
            <a href="/users/sign_up" class="sign-up-button">Regístrate</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/site/home.html.erb
<% if user_signed_in? %>
  <%= link_to "Manage Campaigns!", campaigns_path %>
<% end %>